namespace homewrok1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Can u find the random number which generated by computer?");
            Random rnd = new Random();
            int value = rnd.Next(0, 100);


            for (int i = 0; ; i++)
            {
                Console.Write("enter number = ");
                int a = Convert.ToInt32(Console.ReadLine());
                if (a > value) Console.WriteLine("Generated number is lower");
                if (a < value) Console.WriteLine("Generated number is higher");

                if (a == value)
                {
                    Console.WriteLine("Right");
                    Console.WriteLine("you found in " + i + " turns");

                    break;
                };


            }


        }
    }
}